version: 2.1
jobs:
  build:
    docker:
      - image: circleci/flutter
    steps:
      - checkout
      - run: flutter doctor -v
      - run: flutter analyze
      - run: flutter test --coverage --coverage-path=lcov.info
      - run: bash <(curl -s https://codecov.io/bash)
